app1/urls.py
from django.urls import path

from . import views


app_name = 'app1'

urlpatterns = [
    path('', views.index, name='index'),
    # -------------21.07.12. detail. answer url 부여 -------------------
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name = 'answer_create'),
    #----------------21.07.13. 질문등록 url 부여 ------------------------
    path('question/create/', views.question_create, name='question_create'),
    #----------------21.07.21 수정url --------------------------
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    #------------- 21.07.21 삭제url ---------------------
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    #------------21.07.23 답변 수정 url -------------------
    path('answer/modify/<int:answer_id>', views.answer_modify, name='answer_modify'),
    #------------21.07.23 답변 삭제 url--------------------
    path('answer/delete/<int:answer_id>', views.answer_delete, name='answer_delete'),
    #------------- 21.07.26 오픈템플릿 주소 추가 --------------
    path('testpage3/', views.test, name='test'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from app1 import views
urlpatterns = [
    # ------------상세보기 페이지 추가(21.07.21 유선미)-----------------------

    path('admin/', admin.site.urls),
    path('app1/', include('app1.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),
]

app1/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# 질문과 답변 테이블 생성(21.7.8 유선미 작성)
# 질문 테이블 : Question
# 질문 제목 : subject
# 질문 내용 : content
# 질문 작성일자 : create_date

#--------------------------질문테이블 -------------------------------------------
class Question(models.Model):
    subject = models.CharField(max_length=100)
    content = models.TextField()
    create_date = models.DateTimeField()
#-------------------21.07.21  글쓴이(author)------------------
    # 추가하는 author 컬럼
    # author = 사용자 ID
    #on_delete=models.CASCADE : User에 있는 값이 삭제되면 해당 값과 연결된
    #                           Question 테이블의 데이터를 삭제하라는 의미
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    # modify_date 컬럼 = 수정일자(작성한 질문에 대한)
    # null=True : 해당 컬럼에 null 값 허용
    # blank=True : 폼 데이터 검사시 값이 없어도 된다는 의미.
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.subject

#---------------------------답변테이블--------------------------------------------
# 답변 테이블 : Answer
# 답변 내용 : answer_content
# 답변 작성일자 : create_date
# 질문 제목 : question(어떤 질문에 대한 답변인지 알아야 하기 때문에)
class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)    # 질문이 삭제가 되면 답변도 자동으로 삭제
    answer_content = models.TextField()
    create_date = models.DateTimeField()
    # null=True: 컬럼의 null값 허용
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    modify_date = models.DateTimeField(null=True, blank=True)

app1/forms.py
from django import forms
from app1.models import Question, Answer

# QuestionForm 같은 클래스를 장고 폼이라 부른다.
# 장고폼에는 2가지 폼이 있고
# 일반 폼, 모델 폼 이라는것이 있음.

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question            # model은 table로 해석되어질 수 있다.
        fields = ['subject', 'content']
# ----------------- 21.07.14 질문 등록하기 제목, 내용에 부트스트랩 적용  -----------------------------
# 왜 html에서 적용하지 않고, 모듈에서 적용하는가?
# why? 템플릿 태그 {{ form.as_p}} 때문
#{{form.as_p}} : 모델(테이블)의 정보를 받아 form과 요쇼를 자동으로 생성하는 템플릿 태그

# 테이블 컬럼 숫자에 관계없이 컬럼을 불러올 수 있다는 장점이 있지만
# html(template)단 에서 스타일을 적용하기 힘들다 라는 단점이 있음.
# 이러한 단점을 widgets 속성을  이용해서 해당 탬플릿(html)로딩시
# 클래스 정보를 전달해주는 방식으로 커버한다.
# key 값은 해당 컬럼명으로 value값은 적용할 속성으로 쓴다.
        widgets = {
            'subject' : forms.TextInput(attrs={'class': 'form-control'}),
            'content' : forms.Textarea(attrs={'class': 'form-control', 'rows':10}),

        }

        labels = {
            'subject': '제목',
            'content': '내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['answer_content']
        labels = {
            'answer_content': '답변내용',
        }

app1/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from .models import Question, Answer                #.models : views.py가 속한 경로에서 moels.py를 찾아라
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from app1.forms import QuestionForm, AnswerForm
# 21.07.19 페이징 처리 관련 모듈 import
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required      # 로그인이 안되어 있을 때 로그인 페이지로
from django.contrib import messages



def test(request):
    return render(request, 'app1/template2.html')

def index(request):
    # request: 외부 사용자의 요청을 받아오는 것.
    # render : 템플릿을 로딩할 때 사용.
    # redirect : url로 이동시 사용용    # 사용자가 localhost:8000/app1 페이지 접속이라는 요청을 보냈다.
    # view -> urls에 어떤 함수를 실행해야 하는지를 확인.
    # 21.07.09 질문 목록가져오기
    # view에서 model단에 요청
    # 요청의 내용 : 조회 (Question 테이블/모델 create_date 컬럼을 기준으로
    #               정렬해서 가져옴) -> 그 결과를 question_list 변수에 저장.

    page = request.GET.get('page', '1')

    question_list = Question.objects.order_by('-create_date')   # 질문 제목을 모두 불러와서 ('-')내림차순으로 정렬
    # context라는 변수에 딕셔너리 형태로 question_list key와 value를 저장.
    # 템플릿단에서 해당 데이터를 쉽게 조회하기 위해.
    # 페이징 처리 내용 : 가져온 데이터를 10개씩 보여달라.
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)


    context = {'question_list': page_obj}
    # 받은 요청에 대해(request)
    # app1/question.list.html 템플릿을 열어주고
    # 해당 템플릿에 context 변수의 값을 전송.

    return render(request, 'app1/question_list.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'app1/question_detail.html', context)

# 21.07.23 수정전 백업
# def answer_create(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     question.answer_set.create(answer_content=request.POST.get('answer_content'), create_date = timezone.now())
#
#
#     return redirect('app1:detail', question_id=question.id)   # 답변이 달리면 해당 질문으로 보내줌.id값의 확인 일치여부를 위해해

#21.07.23 answer_create 수정(유선미)
# 기존 answer_create 기능 중 로그인한지 않은 사용자도 답변을 달 수 있다라는 문제점이 발견되어 수정
# author  컬럼이 추가됨에 따라 답변 작성자를 저장하기 위한 코드 수정.

@login_required(login_url='common:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    # 답변 수정은 답변 작성자만 수정 가능하게끔 처리하는 코드

    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('app1:detail', question_id = question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    # form에 있는 내용도 받아와야하지만, question에 있는 키값을 받아야하기 떄문에
    return render(request, 'app1/question_detail.html', context)



# 질문 등록함수 21.07.13 (유선미)/ 07.14 수정
# login_required 데코레이터를 추가함으로써
# 만약 질문등록하기 페이지 이동시 로그인이 안되어있다면
# 로그인페이지로 먼저 이동시킨다.
@login_required(login_url='common:login')
def question_create(request):
    # 수정 내용 : GET, POST 방식에 대한 처리
    # question_form으로 들어올 때
    # 질문을 등록할 때
    # POST 방식인지 GET 방식인지 확인
    # why? 단순히 질문등록 페이지를 오픈한 것인지 아니면 질문등록 페이지에 데이터를 입력해서 저장한 것인지를 구분.
    if request.method == "POST":
        # forms.py에 설정한 QuestionForm 클래스를 호출
        # request.POST :사용자가 입력한 데이터를  받아온다.
        form = QuestionForm(request.POST)
        # 변수 form에 들어온 값이 올바른값(정상적인 값)인지를 확인
        if form.is_valid():
            # 저장을 하기전 잠시 유보.
            # question 변수에 form에서 받아온 데이터는 넣어뒀지만
            # 아직 DB로 저장하지는 않았다.
            question = form.save(commit=False)
            # create_date 컬럼을 따로 입력받지 않은 이유는?
            # 질문등록의 날짜 시간의 경구 현재 시간으로 입력받기 위해
            # view에서 처리.
            question.create_date = timezone.now()
            question.author = request.user
            question.save()
            return redirect('app1:index')
    else:
        form = QuestionForm()
    return render(request, 'app1/question_form.html', {'form': form})



#21.07.21 질문 수정 함수 추가
@login_required(login_url='common:login')
def question_modify(request, question_id):

    question = get_object_or_404(Question, pk=question_id)

    # 본인이 쓴글은 본인만 수정 가능하게

    if request.user != question.author:      # 글쓴이와 현재 접속한 유저 비교
        messages.error(request, '수정권한이 없습니다.')
        return redirect('app1:detail', question_id=question.id)

    # 전송방식이 POST인지를 확인 (question_form으로 접속만한건지
    #                          아니면 데이터를 전송받아왔는지 체크)
    if request.method == "POST":
        # instance = question
        # 인스턴스 파라미터에 question 테이블을 지정해 기존의 값을
        # form에 채워 넣음.
        # 만약 전달받은 데이터가 있다면 전달받은 입력값을 덮어써서
        # QuestionForm을 재생성.
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_date = timezone.now()
            question.save()
            # 수정된 내용 저장을 완료후 question_detail 페이지로 이동
            # 주의사항 : 일반적인 방식으로 redirect 리턴한타면
            #           key값(id값)을 찾을수가 없다.
            #           그러한 상황을 방지하기위해 question_id에 기존 컬럼의 key값을
            #           return
            return redirect('app1:detail', question_id=question.id)
            #                                  (key값 리턴 추가)

    form = QuestionForm(instance=question)
    return render(request, 'app1/question_form.html', {'form': form})

#----------------------21.07.21 질문 삭제 함수 등록.
@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제 권한이 없습니다 작성자를 확인해주세요.')
        return redirect('app1:detail', question_id=question.id)
    question.delete()
    return redirect('app1:index')

#----------------------21.07.23 답변 수정 함수
@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    # answer = get_object_or_404(Answer, pk=answer_id)
    #
    # if request.user == answer.author:
    #     return redirect('app1:detail', answer_id=answer.id)
    #
    # if request.method == "POST":
    #     form = AnswerForm(request.POST)
    #
    #     if form.is_valid():
    #         answer=form.save(commit=False)
    #         answer.author = request.user
    #         answer.modify_date = timezone.now()
    #         answer.save()
    #         return redirect('app1:detail', answer_id=answer.id)
    #
    # form = AnswerForm()
    # return render(request, 'app1/answer_form.html', {'form': form})

    answer = get_object_or_404(Answer, pk=answer_id)
    # 답변 수정은 답변 작성자만 수정 가능하게끔 처리하는 코드
    # 답변 작성자와 로긍니한 유저가 같은지 확인
    if request.user != answer.author:
        # 다르다면 에러 메세지를 템플릿단에 전송
        messages.error(request, '수정 권한이 없습니다.')
        return redirect('app1:detail', question_id = answer.question.id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('app1:detail', question_id=answer.question.id)
    else:
        form = AnswerForm()
    context = {'form': form }
    return render(request, 'app1/answer_form.html', context)

#-------------21.07.23 답변 삭제 함수 등록
@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제 권한이 없습니다 작성자를 확인해주세요.')
        return redirect('app1:detail', answer_id=answer.id)
    answer.delete()
    return redirect('app1:detail')

# def question_create(request):  (백업용/21.07.14)
#     form = QuestionForm()
#     return render(request, 'app1/question_form.html', {'form': form})

templates/app1/answer_form.html
  
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="answer_content">답변내용</label>
            <textarea class="form-control" name="answer_content" id="answer_content"
                      rows="10">{{ form.answer_content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/app1/question_detail.html
{% extends 'base.html'%}
{% block content %}
<script type="text/javascript">
$(document).ready(function(){
    $(".delete").on('click',function(){
        if(confirm("진짜로 삭제하시겠습니다까?")){
            location.href = $(this).data('uri');
        }
    });
});
</script>

<div class="container my-3">
    <!-- 에러 메세지 표시-->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
        {% for msg in messages %}
        <strong>{{msg.tags}}</strong>
        <ul><li>{{ msg.message}}</li></ul>
        {% endfor %}
    </div>

    {% endif%}


    <h2 class="border-bottom py-2">{{ question.subject }}</h2>  <!--질문 이름 들어오는 곳-->
    <!--border-bottom py-2 : padding y축으로 2-->
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line">
                {{ question.content}}
            </div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    <div class="m-2">{{question.author.username}}</div>
                    {{question.create_date}}
                </div>

            </div>
            <!-- 21.07.21 수정버튼 등록
            data-uri : data 접두사라는 것이 붙은 데이터 문자열
            data-uri가 이미지, 영상, 사운드 파일등의 데이터 전송에도 사용할 수 있기 때문
            data-uri : 파일을 문자열로 변환한 것. -->
            <div class="my-3">
                <a href="{% url 'app1:question_modify' question.id %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" data-uri="{% url 'app1:question_delete' question.id%}"
                   class="delete btn btn-sm btn-outline-secondary">삭제</a>
            </div>


        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">
        {{ question.answer_set.count}}개의 답변이 있습니다.
    </h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line">
                {{answer.answer_content}}
            </div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                      <div class="m-2">{{answer.author.username}}</div>
                    {{ answer.create_date}}

                </div>

            </div>
                {% if request.user == answer.author %}
                 <div class="my-3">
                     <a href="{% url 'app1:answer_modify' answer.id %}"
                     class="btn btn-sm btn-outline-secondary">수정</a>
                     <a href="#" data-uri="{% url 'app1:answer_delete' answer.id%}"
                   class="delete btn btn-sm btn-outline-secondary">삭제</a>
                 </div>
                 {% endif%}
        </div>
    </div>

    {% endfor %}

    <form action="{% url 'app1:answer_create' question.id %}" method="post">
    {% csrf_token %}
    {% if form.errors %}        <!-- 빈값이 들어갔거나 잘못된 값이 들어갔을 때 -->
        <div class="alert alert-danger" role="alert">    <!--경고 메세지가 뜨는 영역-->
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}
     <div class="form-group">
    <textarea {% if not user.is_authenticated %}disabled{% endif %}
              name="answer_content" id="answer_content" class="form-control" rows="15"></textarea>
        </div>
        <input type="submit" value="답변등록하기">
    </form>
</form>
</div>
{% endblock%}
{% block script %}


{% endblock %}

templates/app1/question_detail_bak0713.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css'%}">
<h1>{{ question.subject }}</h1>
<P>{{ question.content }}</P>

<h5>{{ question.answer_set.count }}개의 답변이 있습니다.</h5>
<div>
    <ul>
        {% for answer in question.answer_set.all %}
        <li>{{ answer.answer_content }}</li>
        {% endfor %}
    </ul>
</div>

<form action="{% url 'app1:answer_create' question.id %}" method="post">
    {% csrf_token %}

    <textarea name="answer_content" id="answer_content" rows="15"></textarea>
    <input type="submit" value="답변등록하기">
</form>
</body>
</html>

templates/app1/question_form.html
{% extends 'base.html' %}

{% block content%}

<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% if form.errors %}        <!-- 빈값이 들어갔거나 잘못된 값이 들어갔을 때 -->
        <div class="alert alert-danger" role="alert">    <!--경고 메세지가 뜨는 영역-->
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
        </div>
        {% endif %}

        <div class="form-group">
            <!-- label: input 태그와 연계해서 사용되는 태그
                        input 태그를 제어해서 상태를 변경하게 도와주는 태그
                 for : 다른 태그와 결합할 때 사용하는 속성
                        결합하고자 하는 태그의 id값과 같아야한다. -->
            <label for="subject">제목</label>
            <!-- form.컬럼명.value : 오류, 혹은 잘못된 연결 등 예기치 못한 상황이나 사용자의 입력실수가 있었을 때 해당 요소에 값이
                                    있었다면 그 값을 초기화를 암시해주는 템플릿 태그 문법
            default_if_none: 기본값을 설정하는 문법
                                -->
            <input type="text" class="form-control" id="subject" name="subject" value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div>
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">
                    {{ form.content.value|default_if_none:'' }}
            </textarea>


        </div>

        <button type="submit" class="btn btn-primary">저장</button>
    </form>

</div>
{% endblock %}

<!-- form: 입력된 데이터를 전송하기위한 태그.
1. 폼이 있는 페이지 접속.
2. 폼에 내용을 입력.
3. 저장(전송 /속성:submit)인 버튼을 눌렀을 때 폼 안쪽의 모든 데이터를 서버(로컬서버)로 전송.
4. jango에서는 받은 폼 데이터를 처리하기위해 forms.py로 넘겨줌.
5. forms.py 에서 데이터를 받은 후 views.py로 넘겨줌
6. views.py에서 데이터를 처리.
7. 처리 결과에 따라 페이지를 웹 서버에 전송
8. 로컬서버는 받은 페이지를 브라우저에 전송.
9. 브라우저는 받은 페이지를 보여줌

폼태그 속성
action : 폼을 전송할 서버 스크립트(템플릿)파일을 지정.
name : 폼을 식별하기 위한 이름
target : action에서 지정한 스크립트 파일을 현재 창이 아니라 다른 위치에 열도록 지정하는 속성
method : 폼을 서버에 전송할 http 메서드를 정하는 방법(GET OR POST)
        기본값은 GET
-->

templates/app1/question_form_bak0714.html
{% extends 'base.html' %}

{% block content%}

<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">저장</button>
    </form>

</div>
{% endblock %}

templates/app1/question_list.html
{% extends 'base.html'%}
{% load filter %}
{% block content %}


<div class="container my-3">   <!-- 부트스트랩을 사용할 때 해당 클래스 호출해서 이미 설정된 스타일을 사용하는 것.-->

    <!-- 페이징 : 컴퓨터가 데이터를 저장하고 검색하는 메모리관리 기법
    paginator.count : 전체 게시물 개수를 가져옴
    start_index : 현재 페이지의 시작 인덱스
    end_index : 현재 페이지의 끝 인덱스
    일려번호 = 전체 게시물 개수  - 시작인덱스 - 현재인덱스 + 1
    -->
    <table class="table">
        <thead>
        <tr class="text-center thead-dark">
            <th>번호</th>
            <th width="50%">제목</th>
            <th>작성자</th>
            <th>작성일</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list%}
        <tr class="text-center">
            <td>{{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}</td>
            <td class="text-left">
                <a href="{% url 'app1:detail' question.id %}">{{question.subject}}</a>
                {% if question.answer_set.count > 0 %}
                <span class="text-danger">{{ question.answer_set.count }}</span>
                {% endif %}

            </td>
            <td>{{ question.author.username }}</td>
            <td>{{ question.create_date }}</td>


        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
        </table>
    <!--페이징 처리 view 영역 21.07.19-->
        <ul class="pagination justify-content-center">
            <!-- has_previous : 이전 페이지가 있는지 유무를 확인 -->
            {% if question_list.has_previous %}
            <!-- previous_page_number : 이전 페이지 번호-->
            <li class="page-item">
                <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>

            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" herf="#" aria-disabled="true" tabindex="-1"></a>

            </li>
            {% endif %}
            <!-- 페이지 리스트 출력하기-->
            <!-- page_range : 페이지의 범위
                number : 현재 페이지 번호. -->
            {% for page_number in question_list.paginator.page_range %}
            {% if page_number >= question_list.number|add:-2 and page_number <= question_list.number|add:2 %}
                {% if page_number == question_list.number %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="?page={{page_number }}">{{ page_number }}</a>

                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{page_number }}">{{ page_number }}</a>

                </li>
                {% endif %}
            {% endif %}
            {% endfor %}

            <!-- has_previous : 다음 페이지가 있는지 유무를 확인 -->
            {% if question_list.has_next %}
            <!-- next_page_number : 디음 페이지 번호-->
            <li class="page-item">
                <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" herf="#" aria-disabled="true" tabindex="-1"></a>
            </li>
            {% endif %}

        </ul>

        <a href="{%  url 'app1:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
{% endblock %}

templates/app1/question_list_bak0713.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css'%}">
{% if question_list %}
    <ul>
        {%  for question in question_list %}
            <li><a href="{% url 'app1:detail' question.id %}">{{question.subject}}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>게시글이 없습니다.</p>
{% endif %}
</body>
</html>