app1/urls.py
from django.urls import path

from . import views


app_name = 'app1'

urlpatterns = [
    path('', views.index, name='index'),
    # -------------21.07.12. detail. answer url 부여 -------------------
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name = 'answer_create'),
    #----------------21.07.13. 질문등록 url 부여 ------------------------
    path('question/create/', views.question_create, name='question_create'),
    #----------------21.07.21 수정url --------------------------
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    #------------- 21.07.21 삭제url ---------------------
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    #------------21.07.23 답변 수정 url -------------------
    path('answer/modify/<int:answer_id>', views.answer_modify, name='answer_modify'),
    #------------21.07.23 답변 삭제 url--------------------
    path('answer/delete/<int:answer_id>', views.answer_delete, name='answer_delete'),
    #------------- 21.07.26 오픈템플릿 주소 추가 --------------
    path('testpage3/', views.test, name='test'),
]

common/urls.py
from django.urls import path

from . import views  # 회원가입과 관련된 views
from django.contrib.auth import views as auth_views    # 권한과 관련된 로그인 views

app_name = 'common'
# 세션 : 일정시간동안 같은 사용자로 부터 들어오는 요청을 하나의 상태로보고
#        그 상태를 일정하게 유지시키는 기술(사이트 방문자가 사이트에 접속해있는 상태)
#       일정시간 : 사이트에 접속한 시점부터 브라우저 종료까지
# 세션 특징
# 1. 웹 서버에 상태를 유지하기 위한 정보를 저장.
# 2. 웹 서버에 저장되는 쿠키 = 세션 쿠키
urlpatterns =[
    path('signup/', views.signup, name = 'signup'),
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from app1 import views
urlpatterns = [
    # ------------상세보기 페이지 추가(21.07.21 유선미)-----------------------

    path('admin/', admin.site.urls),
    path('app1/', include('app1.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css'%}">
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <title>ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ</title>
</head>
<body>
<!--navbar 추가 21. 07. 16(유선미)-->
{% include "navbar.html" %}
{% block content %}  <!-- 상속을 해준 html에서 구현을 하면 됨.-->
{% endblock %}

</body>
</html>

templates/form_errors.html
    {% if form.errors %}        <!-- 빈값이 들어갔거나 잘못된 값이 들어갔을 때 -->
        {% for field in form %}
            {% for error in field.errors %}
            <!-- 필드오류 출력 / 필드 오류: 입력값 누락, 형식에 맞지 않는 값 입력 오류-->
        <div class="alert alert-danger" role="alert">    <!--경고 메세지가 뜨는 영역-->
                <strong>{{ field.label }}</strong>
                {{ error }}
                </div>
                {% endfor %}
            {% endfor %}
                {% for error in form.non_filed_errors %}
                    <!-- 논필드 오류 출력: 논플드 오류 : 입력값과 관계없이 발생한 오류-->
                    <div class="alert alert-danger" role="alert">    <!--경고 메세지가 뜨는 영역-->
                    <strong>{{ error }}</strong>
                        </div>
                {% endfor %}
        {% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'app1:index' %}">프로젝트</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav mr-auto" >
            <li class="nav-item ">
                {% if user.is_authenticated %}   # session 컨트롤, 현재 로그인의 여부를 판단
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }}(로그아웃)</a>
                        {% else %}
                    <div class="row my-3">
                        <a class="nav-link" href="{% url 'common:login'%}">로그인</a>
                    </div>
                    {% endif %}
            </li>
            <li class="nav-item">
                <div class="row my-3 m-2">
                    <a class="nav-link" href="{% url 'common:signup'%}">회원가입</a>
                </div>
            </li>
            <li class="nav-item">
                <div class="row my-3 m-2">
                    <a class="nav-link" href="{% url 'app1:test' %}">테스트페이지</a>
                </div>
            </li>
        </ul>
    </div>
</nav>